package app.repository;

import org.springframework.data.repository.CrudRepository;

import app.model.Orders;

public interface OrdersRepository extends CrudRepository<Orders, Long> {
  //Autogenerated
}
